searchString = "l"

searcher = new RegExp('^' + searchString, "i")

theKeys = [
    "left ctrl"
    "left shift"
    "left alt"
    "left gui"
    "right ctrl"
    "right shift"
    "right alt"
    "right gui"
    "up arrow"
    "down arrow"
    "left arrow"
    "right arrow"
    "backspace"
    "tab"
    "return"
    "escape"
    "insert"
    "delete"
    "page up"
    "page down"
    "home"
    "end"
    "caps lock"
    "f1"
    "f2"
    "f3"
    "f4"
    "f5"
    "f6"
    "f7"
    "f8"
    "f9"
    "f10"
    "f11"
    "f12"
    "left control"
    "left option"
    "left command"
    "right control"
    "right option"
    "right command"
    "left windows"
    "right windows"
    "enter"
    "ctrl"
    "shift"
    "alt"
    "gui"
    "control"
    "shift"
    "option"
    "command"
    "windows"
]

alert(theEntry) for theEntry in theKeys when searcher.test(theEntry) is true
